fixed NoClassdefFoundError (. was missing in Bundle-Classpath + build.properties)
git-svn-id: https://svn.jfire.org/svn/main/trunk/org.nightlabs.editor2d.viewer.ui@14980 18c61ebf-f106-0410-9e1e-81fb82415b8f